version: "2.2"
services:
  www:
    build: .
    ports:
      - 8080:80
    volumes: 
      - "./progetto_docker:/var/www/html/progetto_docker"
  miodb:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=gesù

  mio_phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
    - PMA_ARBITRARY=1